name: Build and Release Debian Package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential ninja-build libpulse-dev
      
      - name: Configure with CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build package
        run: |
          cmake --build build --target package -v
      
      - name: Upload debian package to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.deb
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          